In [2]:
%load_ext kedro.ipython

[03/04/26 14:08:57] INFO     Using                                                                  ]8;id=570764;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/framework/project/__init__.py\__init__.py]8;;\:]8;id=977397;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/framework/project/__init__.py#269\269]8;;\
                             '/Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv
                             /lib/python3.12/site-packages/kedro/framework/project/rich_logging.yml
                             ' as logging configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=163527;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=305632;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=817800;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=389328;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=657555;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=203813;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#181\181]8;;\
                             /Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer.
                             To set a different path, run '%reload_kedro <project_root>'

[03/04/26 14:08:57] WARNING  /Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/ ]8;id=400457;file:///Users/amadeus.portes/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=796308;file:///Users/amadeus.portes/.local/share/uv/python/cpython-3.12.12-macos-aarch64-none/lib/python3.12/warnings.py#112\112]8;;\
                             lib/python3.12/site-packages/requests/__init__.py:113:
                             RequestsDependencyWarning: urllib3 (2.6.3) or chardet
                             (7.0.0)/charset_normalizer (3.4.4) doesn't match a supported version!
                               warnings.warn(

[03/04/26 14:08:58] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=531349;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py\plugin.py]8;;\:]8;id=239689;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

                    INFO     Kedro project emailanalyzer                                            ]8;id=24950;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=204544;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=782904;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=772945;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#148\148]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=825020;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=220209;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#154\154]8;;\

In [4]:
df = catalog.load('emails')

[03/04/26 14:09:44] INFO     Loading data from emails (CSVDataset)...                          ]8;id=670180;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=324197;file:///Users/amadeus.portes/PythonProjects/spaceflights/emailanalyzer/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

In [5]:
df.head()

  label                                               text
0   ham  Can you bring your laptop tomorrow? I need to ...
1   ham           Did you see the news today? Crazy stuff.
2   ham          What are your plans for the long weekend?
3  spam  REMINDER FROM O2: To get 2.50 pounds free call...
4   ham  Eh u remember how 2 spell his name... Yes i di...

In [6]:
df.columns

Index(['label', 'text'], dtype='object')

In [7]:
df = df.dropna().drop_duplicates(subset=["text"])

In [8]:
df["label"].value_counts()

label
ham     102
spam     51
Name: count, dtype: int64

In [9]:
df["length"] = df["text"].str.len()

In [15]:
df.groupby("label").head()

   label                                               text  length
0    ham  Can you bring your laptop tomorrow? I need to ...      56
1    ham           Did you see the news today? Crazy stuff.      40
2    ham          What are your plans for the long weekend?      41
3   spam  REMINDER FROM O2: To get 2.50 pounds free call...     125
4    ham  Eh u remember how 2 spell his name... Yes i di...      81
5   spam  Last reminder! You have an unpaid charge of £4...     121
6    ham  Happy New Year! Hope this year brings you joy ...      57
11  spam  Loan for any purpose & any amount up to £25,00...     109
15  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
17  spam  Bcm: LIFE INSURANCE - You could be getting muc...     120

In [17]:
df['char_count'] = df['text'].str.len()
df.head()

  label                                               text  length  char_count
0   ham  Can you bring your laptop tomorrow? I need to ...      56          56
1   ham           Did you see the news today? Crazy stuff.      40          40
2   ham          What are your plans for the long weekend?      41          41
3  spam  REMINDER FROM O2: To get 2.50 pounds free call...     125         125
4   ham  Eh u remember how 2 spell his name... Yes i di...      81          81

In [18]:
df.columns

Index(['label', 'text', 'length', 'char_count'], dtype='object')

In [19]:
df.drop(columns=['length'])

    label                                               text  char_count
0     ham  Can you bring your laptop tomorrow? I need to ...          56
1     ham           Did you see the news today? Crazy stuff.          40
2     ham          What are your plans for the long weekend?          41
3    spam  REMINDER FROM O2: To get 2.50 pounds free call...         125
4     ham  Eh u remember how 2 spell his name... Yes i di...          81
..    ...                                                ...         ...
148   ham  As per your request 'Melle Melle (Oru Minnamin...         160
149   ham  URGENT! You have won a 1 week FREE membership ...          76
150   ham          Is that seriously how you spell his name?          41
151  spam  England v Macedonia - dont miss the goals/team...         148
152  spam  Please call our customer service representativ...         147

[153 rows x 3 columns]

In [27]:
import pandas as pd

In [30]:

def add_features(df: pd.DataFrame) -> pd.DataFrame:
    df["word_count"] = df["text"].str.split().str.len()
    df["exclamation_count"] = df["text"].str.count(r"!")
    df["has_url"] = df["text"].str.contains(
        r"http|www|\.com|\.co\.uk", case=False, regex=True
    ).astype(int)
    df["has_money"] = df["text"].str.contains(
        r"\£|\$|\€|free|win|cash|prize|earn|claim|awarded",
        case=False, regex=True
    ).astype(int)
    df["has_phone"] = df["text"].str.contains(
        r"\b0\d{9,10}\b|\b\+\d{10,13}\b", regex=True
    ).astype(int)
    return df

In [32]:
df = add_features(df)

In [33]:
df.head(10)

,label,text,length,char_count,word_count,exclamation_count,has_url,has_money,has_phone
0,ham,Can you bring your laptop tomorrow? I need to ...,56,56,11,0,0,0,0
1,ham,Did you see the news today? Crazy stuff.,40,40,8,0,0,0,0
2,ham,What are your plans for the long weekend?,41,41,8,0,0,0,0
3,spam,REMINDER FROM O2: To get 2.50 pounds free call...,125,125,24,0,0,1,0
4,ham,Eh u remember how 2 spell his name... Yes i di...,81,81,19,0,0,0,0
5,spam,Last reminder! You have an unpaid charge of £4...,121,121,19,1,0,1,0
6,ham,Happy New Year! Hope this year brings you joy ...,57,57,11,1,0,0,0
7,ham,Save me a spot at the table. Be there in 5.,43,43,11,0,0,0,0
8,ham,Don't forget we have practice at 6pm.,37,37,7,0,0,0,0
9,ham,England v Macedonia - dont miss the goals/team...,52,52,9,0,0,0,0

In [35]:
feature_cols = ["char_count", "word_count", "exclamation_count", "has_url", "has_money", "has_phone"]
df.groupby("label")[feature_cols].mean().round(3)

,char_count,word_count,exclamation_count,has_url,has_money,has_phone
label,,,,,,
ham,52.196,10.088,0.245,0.000,0.088,0.000
spam,107.000,18.902,0.765,0.157,0.686,0.314

In [39]:
import re

In [81]:
def _clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " url ", text)
    text = re.sub(r"\£|\$|\€", " money ", text)
    text = re.sub(r"\b\d+\b", " num ", text)
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [88]:
df["clean_text"] = df["text"].apply(_clean_text)
df.head(10)

,label,text,length,char_count,word_count,exclamation_count,has_url,has_money,has_phone,clean,clean_text
0,ham,Can you bring your laptop tomorrow? I need to ...,56,56,11,0,0,0,0,can you bring your laptop tomorrow i need to b...,can you bring your laptop tomorrow i need to b...
1,ham,Did you see the news today? Crazy stuff.,40,40,8,0,0,0,0,did you see the news today crazy stuff,did you see the news today crazy stuff
2,ham,What are your plans for the long weekend?,41,41,8,0,0,0,0,what are your plans for the long weekend,what are your plans for the long weekend
3,spam,REMINDER FROM O2: To get 2.50 pounds free call...,125,125,24,0,0,1,0,reminder from o2 to get num num pounds free ca...,reminder from o2 to get num num pounds free ca...
4,ham,Eh u remember how 2 spell his name... Yes i di...,81,81,19,0,0,0,0,eh u remember how num spell his name yes i did...,eh u remember how num spell his name yes i did...
5,spam,Last reminder! You have an unpaid charge of £4...,121,121,19,1,0,1,0,last reminder you have an unpaid charge of mon...,last reminder you have an unpaid charge of mon...
6,ham,Happy New Year! Hope this year brings you joy ...,57,57,11,1,0,0,0,happy new year hope this year brings you joy a...,happy new year hope this year brings you joy a...
7,ham,Save me a spot at the table. Be there in 5.,43,43,11,0,0,0,0,save me a spot at the table be there in num,save me a spot at the table be there in num
8,ham,Don't forget we have practice at 6pm.,37,37,7,0,0,0,0,don t forget we have practice at 6pm,don t forget we have practice at 6pm
9,ham,England v Macedonia - dont miss the goals/team...,52,52,9,0,0,0,0,england v macedonia dont miss the goals team news,england v macedonia dont miss the goals team news

In [ ]:
def preprocess(x: pd.Series) -> pd.Series:
    x = x.lower()
    x = re.sub(r"httpS+|wwwS+", " url ", text)
    x = re.sub(r"£|$|€",      " money ", text)
    x = re.sub(r"d+",        " num ", text)
    x = re.sub(r"[^ws]",        " ", text)
    return text.strip()